language: java
jdk:
- openjdk8

sudo: false
install: true


script:
  - pwd
  - cd app
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd target
  - ls -al
  - cd ../../
  - pwd
  - ls -al

after_success:
  - pwd
  - ls -al
  - mkdir codedeploy_artifact
  - zip -r csye6225-lab-$TRAVIS_JOB_NUMBER.zip app/target/huskycloud.war infrastructure/aws/codedeploy/appspec.yml
  - ls -al
  - mv csye6225-lab-$TRAVIS_JOB_NUMBER.zip codedeploy_artifact/
  - pwd
  - cd codedeploy_artifact
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al

deploy:
  - provider: s3
    local_dir: codedeploy_artifact
    bucket: $s3_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    on:
      branch: lab1

notifications:
email:
  recipients:
    - dinesh.v@husy.neu.edu
    - kartha.n@husky.neu.edu
    - nelagondanahalli.n@husky.neu.edu
notifications:
    slack: csye6225cloud:MKvTRRJTrkMm3HTD33mRDaIQ
