language: java
jdk:
- openjdk8

sudo: false
install: true


script:
  - pwd
  - cd app
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd target
  - ls -al
  - cd ..
  - pwd
  - ls -al

after_success:
  - pwd
  - ls -al
  - mkdir codedeploy_artifact
  - zip -r csye6225-lab-$TRAVIS_JOB_NUMBER.zip app/target/huskycloud.war infrastructure/aws/codedeploy/appspec.yml
  - ls -al
  - pwd
  - cd codedeploy_artifact
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al  


notifications:
email:
  recipients:
    - dinesh.v@husy.neu.edu
    - kartha.n@husky.neu.edu
    - nelagondanahalli.n@husky.neu.edu
notifications:
    slack: csye6225cloud:MKvTRRJTrkMm3HTD33mRDaIQ
