language: java
jdk:
- openjdk8
services:
  - mysql

sudo: false
install: true

before_install:
  - mysql -e 'CREATE DATABASE csyecloud;'

script:
  - pwd
  - cd app
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -Dspring.profiles.active=aws -Dspring.datasource.username=travis -Dspring.datasource.password=$travis_db_password -B -V
  - cd target
  - ls -al
  - cd ../../
  - pwd
  - ls -al

after_success:
  - pwd
  - ls -al
  - mkdir codedeploy_artifact
  - cp infrastructure/aws/codedeploy/*.sh .
  - cp infrastructure/aws/codedeploy/*.yml .
  - cp app/target/huskycloud.war app/target/ROOT.war
  - sudo rm app/target/huskycloud.war
  - zip -r csye6225-web-app-$TRAVIS_JOB_NUMBER.zip app/target/ROOT.war *.sh *.yml
  - ls -al
  - mv csye6225-web-app-$TRAVIS_JOB_NUMBER.zip codedeploy_artifact/
  - ls -al
  - pwd
  - cd codedeploy_artifact
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al

deploy:
  - provider: s3
    local_dir: codedeploy_artifact
    bucket: $s3_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    on:
      branch: assignment8
  - provider: codedeploy
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    bucket: $s3_bucket
    key: csye6225-web-app-$TRAVIS_JOB_NUMBER.zip
    bundle_type: zip
    application: nvn-codedeploy-app
    deployment_group: NvnCloudDeployGroup
    region: us-east-1
    wait-until-deployed: true
    on:
      branch: assignment8

notifications:
email:
  recipients:
    - dinesh.v@husy.neu.edu
    - kartha.n@husky.neu.edu
    - nelagondanahalli.n@husky.neu.edu
notifications:
    slack: csye6225cloud:MKvTRRJTrkMm3HTD33mRDaIQ
