language: java
jdk:
- openjdk8

sudo: false
install: true

script:
  - pwd
  - cd app
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - cd target
  - ls -al
  - cd ../../
  - pwd
  - ls -al

after_success:
  - pwd
  - ls -al
  - mkdir codedeploy_artifact
  - cp app/target/huskycloud.war infrastructure/aws/codedeploy
  - cd infrastructure/aws/codedeploy
  - pwd
  - ls -al
  - zip -r csye6225-spring2018-$TRAVIS_JOB_NUMBER.zip .
  - ls -al
  - mv csye6225-spring2018-$TRAVIS_JOB_NUMBER.zip ../../../codedeploy_artifact/
  - pwd
  - cd codedeploy_artifact
  - ls -al
  - pwd
  - cd ..
  - pwd
  - ls -al

deploy:
  - provider: s3
    local_dir: codedeploy_artifact
    bucket: $s3_bucket
    region: us-east-1
    skip_cleanup: true
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    on:
      branch: assignment6
  - provider: codedeploy
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    bucket: $s3_bucket
    key: csye6225-spring2018-$TRAVIS_JOB_NUMBER.zip
    bundle_type: zip
    application: nvn-codedeploy-app
    deployment_group: NvnCloudDeployGroup
    region: us-east-1
    on:
      branch: assignment6

notifications:
email:
  recipients:
    - dinesh.v@husy.neu.edu
    - kartha.n@husky.neu.edu
    - nelagondanahalli.n@husky.neu.edu
notifications:
    slack: csye6225cloud:MKvTRRJTrkMm3HTD33mRDaIQ
