language: java
jdk:
- openjdk8

sudo: false
install: true


script:
- pwd
- cd app
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- cd target
- la -al
- cd ..
- pwd


notifications:
email:
  recipients:
    - dinesh.v@husy.neu.edu
    - kartha.n@husky.neu.edu
    - nelagondanahalli.n@husky.neu.edu
notifications:
    slack: csye6225cloud:MKvTRRJTrkMm3HTD33mRDaIQ
