language: java
jdk:
- openjdk8

sudo: false
install: true

script:
- ./mvnw clean install

notifications:
email:
  recipients:
    - dinesh.v@husy.neu.edu
notifications:
    slack: csye6225cloud:MKvTRRJTrkMm3HTD33mRDaIQ
